### bgp global config
asn: 65011
bgp_name: bgp-ganjil

### client config
client_network: 10.11.100.0/24
client_pool: 10.11.100.100-10.11.100.200

### app config
zone:
  port: 8081
  directory: app-ganjil-1

### server
## bgp neighbors
bgp_neighbors:
  - address: "{{ mikrotik_3.address.ovs3int }}"
    remote_as: "{{ hostvars['mikrotik-3-ganjil']['asn'] }}"

bgp_expected_neighbors:
  - "{{ mikrotik_3.address.ovs3int }}"

### haproxy lb7 setup
lb7_haproxy_acl:
  hostname:
    - acl_name: host_app-ganjil
      hostname: app-ganjil.wahaha.lab

    - acl_name: host_app-global
      hostname: app-global.wahaha.lab

    - acl_name: host_app-genap
      hostname: app-genap.wahaha.lab    

  network:
    - acl_name: net_ganjil
      network: "{{ client_network }}"

    - acl_name: net_genap
      network: "{{ hostvars['lb7-2-genap']['client_network'] }}"

lb7_haproxy_vhosts: 
  - backend: app-ganjil
    servers:
      - "{{ lb4_1.address.ovs5int }}:{{ zone.port }} check"
    rule: host_app-ganjil net_ganjil

  - backend: app-global
    servers:
      - "{{ lb4_1.address.ovs5int }}:{{ global.port }} check"
      - "{{ lb4_2.address.ovs6int }}:{{ global.port }} check backup"
      - "{{ lb4_3.address.ovs6int }}:{{ global.port }} check backup"
    rule: host_app-global

  - backend: app-genap
    servers:
      - "{{ lb4_2.address.ovs6int }}:{{ global.port }} check"
      - "{{ lb4_3.address.ovs6int }}:{{ global.port }} check"
    rule: host_app-genap net_genap

lb4_haproxy_vhosts: 
  - backend: global-app
    frontend: global-ingress
    frontend_port: "{{ global.port }}" 
    servers:
      - "{{ app_1.address.ovs7int }}:{{ global.port }} check"

  - backend: ganjil-app
    frontend: ganjil-ingress
    frontend_port: "{{ zone.port }}" 
    servers: 
      - "{{ app_1.address.ovs7int }}:{{ zone.port }} check"