### bgp global config
asn: 65011
bgp_name: bgp-ganjil

### network pool config
## dhcp client
client_network: 10.11.100.0/24
client_pool: 10.11.100.100-10.11.100.200

### app config
zone:
  port: 8081
  directory: app-ganjil-1

### server
## bgp neighbors
bgp_frr:
  - name: "{{ asn }}"
    router_id: "{{ ansible_host }}"
    neighbor:
      - "{{ mikrotik_3.address.ovs3int }} remote-as {{ hostvars['mikrotik-3-ganjil']['asn'] }}"
    network:
      - "{{ anycast_ip }}/32"

bgp_expected_neighbors:
  - "{{ mikrotik_3.address.ovs3int }}"

### haproxy lb7 setup
haproxy_acl:
## just used in lb7
  hostname:
    - acl_name: host_app-ganjil
      hostname: app-ganjil.wahaha.lab

    - acl_name: host_app-global
      hostname: app-global.wahaha.lab

## just used in lb4
  network:
    - acl_name: net_ganjil
      network: "{{ client_network }}"

    - acl_name: net_genap
      network: "{{ hostvars['lb7-2-genap']['client_network'] }}"

## defaul health with http/1.1 response
lb7_haproxy_healthcheck:
  - name: app-ganjil
    uri: /
    hostname: app-ganjil.wahaha.lab

  - name: app-global
    uri: /
    hostname: app-global.wahaha.lab

lb7_haproxy_vhosts:
  - backend: app-ganjil
    servers:
      - "{{ app_1.address.ovs7int }}:{{ zone.port }} check healthcheck app-ganjil"
    rule: host_app-ganjil

  - backend: app-global
    servers:
      - "{{ app_1.address.ovs7int }}:{{ app_global.port }} check healthcheck app-global"
    rule: host_app-global

lb4_haproxy_vhosts:
  - backend: lb7-genap
    servers:
      - "{{ lb7_1.address.ovs5int }}:{{ hostvars['lb7-1-ganjil']['haproxy']['port_in'] }} check backup" 
      - "{{ lb7_2.address.ovs6int }}:{{ hostvars['lb7-2-genap']['haproxy']['port_in'] }} check"
      - "{{ lb7_3.address.ovs6int }}:{{ hostvars['lb7-3-genap']['haproxy']['port_in'] }} check"
    rule: net_genap

  - backend: lb7-ganjil
    servers:
      - "{{ lb7_1.address.ovs5int }}:{{ hostvars['lb7-1-ganjil']['haproxy']['port_in'] }} check" 
      - "{{ lb7_2.address.ovs6int }}:{{ hostvars['lb7-2-genap']['haproxy']['port_in'] }} check backup"
      - "{{ lb7_3.address.ovs6int }}:{{ hostvars['lb7-3-genap']['haproxy']['port_in'] }} check backup"
    rule: net_ganjil || host_app-global