### bgp global config
asn: 65011
bgp_name: bgp-ganjil

### client config
client_network: 10.11.100.0/24
client_pool: 10.11.100.100-10.11.100.200

### app config
zone:
  port: 8081
  directory: app-ganjil-1

### server
## bgp neighbors
bgp_neighbors:
  - address: "{{ mikrotik_3.address.ovs3int }}"
    remote_as: "{{ hostvars['mikrotik-3-ganjil']['asn'] }}"