## bgp config
asn: 65012
bgp_name: bgp-genap

## client config
client_network: 10.12.100.0/24
client_pool: 10.12.100.100-10.12.100.200

## app config
zone:
  port: 8081
  directory: app-genap-1

### mikrotik
address_list:
## advertised network
  - list: bgp-network
    address: 10.12.10.0/24

  - list: bgp-network
    address: 10.12.0.0/30

  - list: bgp-network
    address: 10.15.100.10/32

  - list: bgp-network
    address: 10.15.0.0/30
##

### server
## bgp neighbors
bgp_neighbors:
  - address: "{{ mikrotik_4.address.ovs3int }}"
    remote_as: "{{ hostvars['mikrotik-4-genap']['asn'] }}"