## bgp config
asn: 65012
bgp_name: bgp-genap

## client config
client_network: 10.12.100.0/24
client_pool: 10.12.100.100-10.12.100.200

## app config
zone:
  port: 8081
  directory: app-genap-1

### server
## bgp neighbors
bgp_neighbors:
  - address: "{{ mikrotik_4.address.ovs3int }}"
    remote_as: "{{ hostvars['mikrotik-4-genap']['asn'] }}"

bgp_expected_neighbors:
  - "{{ mikrotik_4.address.ovs3int }}"

### haproxy lb7 setup
haproxy_vhosts:
  - hostname: app-genap.wahaha.lab
    backend: app-genap
    servers:
      - "{{ app_2_lb.address.ovs7int }}:{{ zone.port }} check"
      - "{{ app_3_lb.address.ovs7int }}:{{ zone.port }} check"

  - hostname: app-global.wahaha.lab
    backend: app-global
    servers:
      - "{{ app_1.address.ovs7int }}:{{ global.port }} check backup"
      - "{{ app_2_lb.address.ovs7int }}:{{ global.port }} check"
      - "{{ app_3_lb.address.ovs7int }}:{{ global.port }} check"