## bgp config
asn: 65012
bgp_name: bgp-genap

### network pool config
## dhcp client
client_network: 10.12.100.0/24
client_pool: 10.12.100.100-10.12.100.200

## app config
zone:
  port: 8081
  directory: app-genap-1

### server
## bgp neighbors
bgp_frr:
  - name: "{{ asn }}"
    router_id: "{{ ansible_host }}"
    neighbor:
      - "{{ mikrotik_4.address.ovs3int }} remote-as {{ hostvars['mikrotik-4-genap']['asn'] }}"
    network:
      - "{{ anycast_ip }}/32"

bgp_expected_neighbors:
  - "{{ mikrotik_4.address.ovs3int }}"

### haproxy lb7 setup
haproxy_acl:
  hostname:
    - acl_name: host_app-genap
      hostname: app-genap.wahaha.lab

    - acl_name: host_app-global
      hostname: app-global.wahaha.lab

  network:
    - acl_name: net_genap
      network: "{{ client_network }}"

    - acl_name: net_ganjil
      network: "{{ hostvars['lb7-1-ganjil']['client_network'] }}"

lb7_haproxy_healthcheck:
  - name: app-global
    uri: /
    hostname: app-global.wahaha.lab

  - name: app-genap
    uri: /
    hostname: app-genap.wahaha.lab

lb7_haproxy_vhosts:
  - backend: app-genap
    servers:
      - "{{ app_2_lb.address.ovs7int }}:{{ zone.port }} check healthcheck app-genap"
      - "{{ app_3_lb.address.ovs7int }}:{{ zone.port }} check healthcheck app-genap"
    rule: host_app-genap

  - backend: app-global
    servers:
      - "{{ app_2_lb.address.ovs7int }}:{{ app_global.port }} check healthcheck app-global"
      - "{{ app_3_lb.address.ovs7int }}:{{ app_global.port }} check healthcheck app-global"
    rule: host_app-global

lb4_haproxy_vhosts:
  - backend: lb7-genap
    servers:
      - "{{ lb7_1.address.ovs6int }}:{{ hostvars['lb7-1-ganjil']['haproxy']['port_in'] }} check backup" 
      - "{{ lb7_2.address.ovs5int }}:{{ hostvars['lb7-2-genap']['haproxy']['port_in'] }} check"
      - "{{ lb7_3.address.ovs5int }}:{{ hostvars['lb7-3-genap']['haproxy']['port_in'] }} check"
    rule: net_genap || host_app-global

  - backend: lb7-ganjil
    servers:
      - "{{ lb7_1.address.ovs6int }}:{{ hostvars['lb7-1-ganjil']['haproxy']['port_in'] }} check" 
      - "{{ lb7_2.address.ovs5int }}:{{ hostvars['lb7-2-genap']['haproxy']['port_in'] }} check backup"
      - "{{ lb7_3.address.ovs5int }}:{{ hostvars['lb7-3-genap']['haproxy']['port_in'] }} check backup"
    rule: net_ganjil