#netbox_url: http://10.9.0.3:30080
#netbox_token: nbt_dYvux7kptwBG.Uxc1k4MzFTIaeRBVury0OekazrjzALhQaUnvCu9C

ansible_connection: ansible.netcommon.network_cli
ansible_network_os: community.routeros.routeros
ansible_user: admin

## mikrotik api
pass: 123
user: tes

## BGP config
# bgp_template:
#   - name: default

bgp_instance:
  - name: "{{ inventory_hostname }}"
    router-id: "{{ ansible_host }}"
    as: "{{ asn }}"

# bgp_connection:
#   - name: "{{ bgp_name }}"
