ansible_connection: ansible.netcommon.network_cli
ansible_network_os: community.routeros.routeros
ansible_user: admin
ansible_gather_facts: false

## mikrotik api
pass_mikrotik: 123
user_mikrotik: tes

