[netbox]
localhost ansible_connection=local

[mikrotik]
mikrotik-1-ganjil ansible_host=192.168.11.85
mikrotik-2-genap ansible_host=192.168.11.84
mikrotik-3-ganjil ansible_host=192.168.11.83
mikrotik-4-genap ansible_host=192.168.11.82

[server:children]
lb4
lb7
app

[lb4]
lb4-1-ganjil ansible_host=192.168.11.49
lb4-2-genap ansible_host=192.168.11.53
lb4-3-genap ansible_host=192.168.11.50

[lb7]
lb7-1-ganjil ansible_host=192.168.11.51
lb7-2-genap ansible_host=192.168.11.46
lb7-3-genap ansible_host=192.168.11.45

[app]
app-1-ganjil ansible_host=192.168.11.52
app-2-lb-genap ansible_host=192.168.11.47
app-3-lb-genap ansible_host=192.168.11.48
