[netbox]
localhost ansible_connection=local

[mikrotik]
mikrotik-1 ansible_host=192.168.11.85
mikrotik-2 ansible_host=192.168.11.84
mikrotik-3 ansible_host=192.168.11.83
mikrotik-4 ansible_host=192.168.11.82

