---
- name: mikrotik config
  hosts: mikrotik
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      handle_absent_entries: "remove"
      handle_entries_content: "remove_as_much_as_possible"
  roles:
    - presetup-mikrotik
    - ipaddress-mikrotik
    - dhcp-mikrotik
    - bgp-mikrotik
  tags:
    - mikrotik
- name: lb7 config
  hosts: lb7
  roles:
    - presetup-lb7
    - frr
    - haproxy
  tags:
    - lb7
- name: lb4 config
  hosts: lb4
  roles:
    - haproxy
  tags:
    - lb4
- name: app config
  hosts: app
  roles:
    - web-app
  tags:
    - app
