interfaces:
  - default-name: ether1
    comment: 'remote'

  - default-name: ether2
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment:

  - default-name: 'ether5'
    comment: 'client'

ip_address:
  - interface: ether2
    address: "{{ mikrotik_1.address.ovs1int }}/30"
    comment: 'to mk3'

  - interface: ether3
    address: "{{ mikrotik_1.address.ovs2int }}/30"
    comment: 'to mk4'

  - interface: ether5
    address: "{{ mikrotik_1.address.ovs4int }}/24"

bgp_connection:

## IBGP
  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-3-ganjil']['asn'] }}"
    local.role: ibgp
    remote.address: "{{ mikrotik_3.address.ovs1int }}"

## EBGP
  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-4-genap']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ mikrotik_4.address.ovs2int }}"
