interfaces:
  - default-name: ether1
    comment: 'remote'

  - default-name: ether2
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment: 'server-interzone'

  - default-name: 'ether5'
    comment: 'not used'

ip_address:
  - interface: ether2
    comment: 'to mk2'
    address: "{{ mikrotik_4.address.ovs1int }}/30"

  - interface: ether3
    comment: 'to mk1'
    address: "{{ mikrotik_4.address.ovs2int }}/30"

  - interface: ether4
    comment: 'server-interzone'
    address: "{{ mikrotik_4.address.ovs3int }}/24"

  # - interface: ether5
  #   comment: 'server-outerzone'
  #   address: "{{ mikrotik_4.address.ovs4int }}/24"

bgp_instance:
  - name: "{{ inventory_hostname }}"
    router-id: "{{ ansible_host }}"
    as: "{{ asn }}"
    multipath: 2

bgp_connection:

## IBGP
  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['lb4-2-genap']['asn'] }}"
    local.role: ibgp-rr
    remote.address: "{{ lb4_2.address.ovs3int }}"
    output.network: bgp-network
    nexthop-choice: force-self
    hold-time: 3
    keepalive-time: 1

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['lb4-3-genap']['asn'] }}"
    local.role: ibgp-rr
    remote.address: "{{ lb4_3.address.ovs3int }}"
    output.network: bgp-network
    nexthop-choice: force-self
    hold-time: 3
    keepalive-time: 1

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-2-genap']['asn'] }}"
    local.role: ibgp-rr
    remote.address: "{{ mikrotik_2.address.ovs1int }}"
    output.network: bgp-network
    nexthop-choice: force-self
    hold-time: 3
    keepalive-time: 1


## EBGP
  # - name: "{{ bgp_name }}"
  #   instance: "{{ inventory_hostname }}"
  #   as: "{{ asn }}"
  #   remote.as: "{{ hostvars['lb4-1-ganjil']['asn'] }}"
  #   local.role: ebgp
  #   remote.address: "{{ lb4_1.address.ovs4int }}"
  #   output.network: bgp-network
  #   hold-time: 3
  #   keepalive-time: 1

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-1-ganjil']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ mikrotik_1.address.ovs2int }}"
    output.network: bgp-network
    hold-time: 3
    keepalive-time: 1

address_list:
  - list: bgp-network
    address: 10.12.10.0/24

  - list: bgp-network
    address: 10.12.0.0/30

  - list: bgp-network
    address: 10.15.100.10/32

  - list: bgp-network
    address: 10.15.0.0/30

  # - list: bgp-network
  #   address: 10.15.10.0/24