interfaces:
  - default-name: 'ether1'
    comment: 'remote'

  - default-name: 'ether2'
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment: 'server-interzone'

  - default-name: 'ether5'
    comment: 'server-outerzone'

ip_address:
  - interface: ether2
    comment: 'to mk2'
    address: "{{ mikrotik_4.address.ovs1int }}"

  - interface: ether3
    comment: 'to mk1'
    address: "{{ mikrotik_4.address.ovs2int }}"

  - interface: ether4
    comment: 'server-interzone'
    address: "{{ mikrotik_4.address.ovs3int }}"

  - interface: ether5
    comment: 'server-outerzone'
    address: "{{ mikrotik_4.address.ovs4int }}"