interfaces:
  - default-name: ether1
    comment: 'remote'

  - default-name: ether2
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment: 'server-interzone'

  - default-name: 'ether5'
    comment: 'not used'

ip_address:
  - interface: ether2
    comment: 'to mk2'
    address: "{{ mikrotik_4.address.ovs1int }}/30"

  - interface: ether3
    comment: 'to mk1'
    address: "{{ mikrotik_4.address.ovs2int }}/30"

  - interface: ether4
    comment: 'server-interzone'
    address: "{{ mikrotik_4.address.ovs3int }}/24"

bgp_instance:
  - name: "{{ inventory_hostname }}"
    router-id: "{{ ansible_host }}"
    as: "{{ asn }}"
    multipath: 2

bgp_connection:

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['lb7-2-genap']['asn'] }}"
    local.role: ibgp-rr
    remote.address: "{{ lb7_2.address.ovs3int }}"
    output.network: bgp-network
    nexthop-choice: force-self
    hold-time: 3s
    keepalive-time: 1s

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['lb7-3-genap']['asn'] }}"
    local.role: ibgp-rr
    remote.address: "{{ lb7_3.address.ovs3int }}"
    output.network: bgp-network
    nexthop-choice: force-self
    hold-time: 3s
    keepalive-time: 1s

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-2-genap']['asn'] }}"
    local.role: ibgp-rr
    remote.address: "{{ mikrotik_2.address.ovs1int }}"
    output.network: bgp-network
    nexthop-choice: force-self
    hold-time: 3s
    keepalive-time: 1s

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-1-ganjil']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ mikrotik_1.address.ovs2int }}"
    output.network: bgp-network
    hold-time: 3s
    keepalive-time: 1s

address_list:
  - list: bgp-network
    address: 10.12.10.0/24

  - list: bgp-network
    address: 10.12.0.0/30

  # - list: bgp-network
  #   address: "{{ anycast_ip }}"

  - list: bgp-network
    address: 10.15.0.0/30
