interfaces:
  - default-name: ether1
    comment: 'remote'

  - default-name: ether2
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment: 'not used'

  - default-name: 'ether5'
    comment: 'client'

ip_address:
  - interface: ether2
    address: "{{ mikrotik_2.address.ovs1int }}/30"
    comment: 'to mk4'

  - interface: ether3
    address: "{{ mikrotik_2.address.ovs2int }}/30"
    comment: 'to mk3'

  - interface: ether5
    address: "{{ mikrotik_2.address.ovs4int }}/24"

bgp_connection:

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-4-genap']['asn'] }}"
    local.role: ibgp
    remote.address: "{{ mikrotik_4.address.ovs1int }}"
    hold-time: 3s
    keepalive-time: 1s
    output.network: bgp-network

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-3-ganjil']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ mikrotik_3.address.ovs2int }}"
    hold-time: 3s
    keepalive-time: 1s
    output.network: bgp-network

dhcp_server:
  - name: dhcp-genap
    interface: ether5
    address-pool: dhcp-pool-genap

dhcp_pool:
  - name: dhcp-pool-genap
    ranges: "{{ client_pool }}"

dhcp_network:
  - address: "{{ client_network }}"
    gateway: "{{ mikrotik_2.address.ovs4int }}"
    dns-server: "{{ mikrotik_2.address.ovs4int }}"

address_list:
  - list: bgp-network
    address: "{{ client_network }}"

## not used
# firewall_nat:
#   - chain: srcnat
#     action: masquerade
#     src-address: 10.12.100.0/24
#     dst-address: 10.15.100.10/32
#     disabled: yes