interfaces:
  - default-name: 'ether1'
    comment: 'remote'

  - default-name: 'ether2'
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment:

  - default-name: 'ether5'
    comment: 'client'

ip_address:
  - interface: ether2
    address: "{{ mikrotik_2.address.ovs1int }}"
    comment: 'to mk4'

  - interface: ether3
    address: "{{ mikrotik_2.address.ovs2int }}"
    comment: 'to mk3'

  - interface: ether5
    address: "{{ mikrotik_2.address.ovs4int }}"
