interfaces:
  - default-name: ether1
    comment: 'remote'

  - default-name: ether2
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment:

  - default-name: 'ether5'
    comment: 'client'

ip_address:
  - interface: ether2
    address: "{{ mikrotik_2.address.ovs1int }}/30"
    comment: 'to mk4'

  - interface: ether3
    address: "{{ mikrotik_2.address.ovs2int }}/30"
    comment: 'to mk3'

  - interface: ether5
    address: "{{ mikrotik_2.address.ovs4int }}/24"

bgp_connection:

## iBGP
  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-4-genap']['asn'] }}"
    local.role: ibgp
    remote.address: "{{ mikrotik_4.address.ovs1int }}"
    output.network: no

## eBGP
  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-3-ganjil']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ mikrotik_3.address.ovs2int }}"


dhcp_server:
  - name: dhcp-genap
    interface: ether5
    address-pool: dhcp-pool-genap

dhcp_pool:
  - name: dhcp-pool-genap
    ranges: 10.12.100.100-10.12.100.200

dhcp_network:
  - address: 10.12.100.0/24
    gateway: 10.12.100.1
    dns-server: 10.12.100.1

address_list:
  - list: bgp-network
    address: 10.12.100.0/24

firewall_nat:
  - chain: srcnat
    action: masquerade
    src-address: 10.12.100.0/24