ip_address:
  - interface: ether2
    address: 10.11.0.1/30
    comment: 'to mk3'

  - interface: ether3
    address: 10.15.0.1/30
    comment: 'to mk4'

  - interface: ether5
    address: 10.11.100.1/24
