interfaces:
  - default-name: ether1
    comment: 'remote'

  - default-name: ether2
    comment: 'interzone'

  - default-name: 'ether3'
    comment: 'outerzone'

  - default-name: 'ether4'
    comment: 'server-interzone'

  - default-name: 'ether5'
    comment: 'server-outerzone'

ip_address:
  - interface: ether2
    comment: 'to mk1'
    address: "{{ mikrotik_3.address.ovs1int }}/30"

  - interface: ether3
    comment: 'to mk2'
    address: "{{ mikrotik_3.address.ovs2int }}/30"

  - interface: ether4
    comment: 'server-interzone'
    address: "{{ mikrotik_3.address.ovs3int }}/24"

  - interface: ether5
    comment: 'server-outerzone'
    address: "{{ mikrotik_3.address.ovs4int }}/24"

bgp_connection:

## IBGP
  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['lb4-1-ganjil']['asn'] }}"
    local.role: ibgp
    remote.address: "{{ lb4_1.address.ovs3int }}"

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-1-ganjil']['asn'] }}"
    local.role: ibgp
    remote.address: "{{ mikrotik_1.address.ovs1int }}"


## EBGP
  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['lb4-2-genap']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ lb4_2.address.ovs4int }}"

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['lb4-3-genap']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ lb4_3.address.ovs4int }}"

  - name: "{{ bgp_name }}"
    instance: "{{ inventory_hostname }}"
    as: "{{ asn }}"
    remote.as: "{{ hostvars['mikrotik-2-genap']['asn'] }}"
    local.role: ebgp
    remote.address: "{{ mikrotik_2.address.ovs2int }}"