- name: Create loopback interface
  command:
    cmd: ip link add anycast0 type dummy
  register: anycast_interface
  failed_when:
    - anycast_interface.rc != 0
    - "'File exists' not in anycast_interface.stderr"
  changed_when: anycast_interface.rc == 0

- name: Bring anycast interface up
  command:
    cmd: ip link set anycast0 up
  changed_when: false

- name: Configure Anycast VIP
  command:
    cmd: "ip addr replace {{ anycast_ip }}/32 dev anycast0"
  changed_when: false

- name: Add Anycast route
  command:
    cmd: "ip route replace {{ anycast_ip }}/32 dev anycast0"
  changed_when: false
