- name: bgp configuration
  hosts: mikrotik
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      handle_absent_entries: "remove"
      handle_entries_content: "remove_as_much_as_possible"

  tasks:

    # - name: create bgp template 
    #   community.routeros.api_modify:
    #     path: routing bgp template
    #     data: "{{ bgp_template }}"
    #   when:
    #     - bgp_template is defined
    #     - bgp_template | length > 0
      # delegate_to: mikrotik-1-ganjil
      # run_once: true

    - name: create bgp instance
      community.routeros.api_modify:
        path: routing bgp instance
        data: "{{ bgp_instance }}"
      when: 
        - bgp_instance is defined
        - bgp_instance | length > 0
      # delegate_to: mikrotik-1-ganjil
      # run_once: true

    - name: create bgp connection
      community.routeros.api_modify:
        path: routing bgp connection
        data: "{{ bgp_connection }}"
      when: 
        - bgp_connection is defined
        - bgp_connection | length > 0

      # delegate_to: mikrotik-3-ganjil
      # run_once: true

    # - name: debug
    #   debug:
    #     msg: "{{ ibgp_connection }}"

- name: Configure FRR
  hosts: lb4

  tasks:
    - name: Deploy FRR configuration
      ansible.builtin.template:
        src: ../templates/frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: "0640"
      notify: Restart FRR

  handlers:
    - name: Restart FRR
      ansible.builtin.systemd:
        name: frr
        state: restarted

