- name: pre setup
  hosts: mikrotik
  gather_facts: false
  tasks:

    - name: set user api
      community.routeros.command:
        commands:
          - /user add name="{{ user }}" password="{{ pass }}" group=full
      changed_when: false

    - name: set system identity
      community.routeros.command:
        commands:
          - /system/identity/set name="{{inventory_hostname}}"
      changed_when: false

    - name: allow resolver
      community.routeros.command:
        commands:
          - /ip dns set allow-remote-requests=yes
      changed_when: false
