name: test runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, lab-rumah]

    steps:
      - name: check runner
        run: |
          hostname
          uname -a
          python3 --version
          ~/global-venv/bin/ansible --version

      - name: checkout repo
        uses: actions/checkout@v7
        
      - name: check ansible
        run: |
          ~/global-venv/bin/ansible --version
          ~/global-venv/bin/ansible-inventory -i ./inventory.ini --graph

      - name: ping all remote host
        run: |
          ~/global-venv/bin/ansible all -m ping
